### ISSUE TITLE
Don't enhance precompile with yarn install

### ISSUE THREAD

**Issue by tomdracz** [shakacode/shakapacker#125]
Running `yarn:install` during `asset:precompile` might be bit too magical. In the same way as we don't run `bundle install`, we shouldn't run `yarn install`.

`yarn:install` being ran adds some time to the compile. On Heroku also, by default it will reinstall all packages even if they have been previously cached. Not good.

Prepping of Shakapacker 7 might be good time to get rid of this behaviour:

TODO:
- Remove `yarn:install` and `webpacker:yarn_install` tasks
- Don't enhance  `assets:precompile` tasks with yarn install (ref https://github.com/shakacode/shakapacker/blob/master/lib/tasks/yarn.rake#L36-L38 and https://github.com/shakacode/shakapacker/blob/master/lib/tasks/webpacker/compile.rake#L12)
- Provide instructions for re-implementing enhanced tasks if users want to keep the old behaviour (pretty much requires user to create a task like https://github.com/shakacode/shakapacker/blob/master/lib/tasks/yarn.rake)

**Comment by tomdracz** [comment]
@justin808 seems reasonable to you?

**Comment by jherdman** [comment]
Can I take this on if it's deemed as reasonable?

**Comment by tomdracz** [comment]
@jherdman All yours!

**Comment by tagliala** [comment]
Hi,

> Prepping of Shakapacker 7 might be good time to get rid of this behaviour:

I would have expected a change like this landing in v7

Would it be a better assumption that Shakapacker uses versioning approach à-la Rails, with potential breaking changes between minor releases?

**Comment by justin808** [comment]
@tagliala, no, we intend to use Semantic Versioning.

Did this break your build?  We'll release a v7 fairly soon, over the next couple of months, mainly renaming files to Shakapacker.

**Comment by tagliala** [comment]
Hi @justin808, thanks for your response

> Did this break your build?

Depends on the build. On Heroku it is fine and it is also desirable because of the reason in the opening post

However, I'm also using Capistrano, and the deploy recipe was counting on `assets:precompile` to run yarn install

So when I try to deploy with 6.4 I get:
```
COMPILATION FAILED:
EXIT STATUS: pid 24991 exit 1
OUTPUTS:
yarn run v1.22.18
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command "webpack" not found.
```

I know that it makes much more sense to have `yarn install` together with `bundle install` and that there is a [Capistrano extension](https://github.com/j-arnaiz/capistrano-yarn) for yarn, but I was not expecting a minor update preventing to deploy without investing time in improving the recipe and adding a new dependency

**Comment by tomdracz** [comment]
@justin808 might consider restoring this with deprecation notice. Definitely didn't plan for this to go out before v7 so we jumped the gun here

**Comment by justin808** [comment]
I'm ok with that. 

If you get master ready, I'll release.

**Comment by januszm** [comment]
Unfortunately, this change causes problems on Amazon Elastic Beanstalk where `assets:precompile` runs automatically during deployment and yarn install helps a lot here. What's more, deprecation warning is actually an `[ERROR]`, not warning, and this in turn causes Elastic Beanstalk deployment to be terminated. Could you change it to normal log and not error? It is probably the exit code issued at the end of this operation.

**Comment by justin808** [comment]
@januszm can you try 6.5.0? I believe the fix https://github.com/shakacode/shakapacker/pull/140 went out in 6.5.

**Comment by januszm** [comment]
Actually, please consider not deprecating and removing it in future versions. Instead, we can add a configuration option and show the deprecation message only if the configuration is not set. For example: `yarn_install: true/false` , if true, it behaves as usual, if false it does not yarn install.

> On Heroku also, by default it will reinstall all packages even if they have been previously cached. Not good.

Looks like this change is mostly wanted by Heroku users, but at the same time it is unwanted by Amazon Elastic Beanstalk users. It's not for me to judge which platform is more important but I expect a lot of people/teams having troubles because of this change and we can simply make it configurable instead deprecating.

**Comment by januszm** [comment]
@justin808  I'm on 6.5 and it still breaks builds on AWS

**Comment by januszm** [comment]
I'm sorry about the confusion regarding the log message guys, obviously the Warning cannot cause exit 1 or 2. Amazon EB somehow merges this log message with a general failure report for the build and it all looks like below:

```
[ERROR] An error occurred during execution of command [self-startup] - [rake tasks]. Stop running the command. Error: running rake task assets:precompile failed with error command bundle exec rake assets:precompile failed with error Command /bin/su webapp -c bundle exec rake assets:precompile failed with error exit status 1. Stderr:Shakapacker - Automatic installation of yarn packages is deprecated
Automatic installation of yarn packages when assets are precompiled is deprecated and will be removed in Shakapacker v7.
```
the root cause was somewhere else, AWS just "promoted" the Shakapacker deprecation message to be the root cause of the problem.

**Comment by justin808** [comment]
I just created PR #236 to allow an ENV SHAKAPACKER_YARN_INSTALL == false to skip the yarn install with assets:precompile.
