### ISSUE TITLE
Why do we have the PnpWebpackPlugin as a default?

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#16]
The PnpWebpackPlugin was added by @gauravtiwari on

https://github.com/rails/webpacker/commit/e95dd724ea3a385b9cc6935c3a07a34f1d1f9657#diff-1701de23f718ce36149c9b23e2db08caR14

Given the long discussion in https://github.com/yarnpkg/rfcs/pull/101

Do we really need the PnpWebpackPlugin as a default?

What problem does it solve?

**Comment by tomdracz** [comment]
Since we're targeting Webpacker 5 we should be able to remove this as PnP is supported by default https://webpack.js.org/migrate/5/#clean-up-configuration

Not using PnP in any of my projects so don't quite have repro case to test against if we decide to remove it but apparently just getting rid of it is all that's needed

**Comment by Judahmeek** [comment]
Fixed by #21
