### ISSUE TITLE
css modules are not currently supported

### ISSUE THREAD

**Issue by skyksandr** [shakacode/shakapacker#178]
A bug is a crash or incorrect behavior. If you have a debugging or troubleshooting question, please open a discussion on [Discussions Tab](https://github.com/shakacode/shakapacker/discussions).

Ruby version: 3.1.2
Rails version: 7.0.3.1
Webpacker version: 6.5.0

Expected behavior:
To support css modules out of the box

Actual behavior:
css modules are not supported. When attempting to import from 
`import styles from './styles.module.scss'`
or
`import * as styles from './styles.module.scss'`
styles are either undefined or value under className is undefined.

Small, reproducible repo:

---

I was searched through all internet and was unable to find anything related. So let this issue serve also the purpose of info for those who face the same problem

---

To fix it we need to slightly change `css-loader` options and add `modules` to it:
```
options: {
  sourceMap: true,
  importLoaders: 2,
  modules: { auto: true }
}
```

or:
```
// Patch css-loader rule to support css-modules
const cssLoader = require.resolve('css-loader')
webpackConfig.module.rules.forEach(rule => {
  rule?.use?.forEach(loader => {
    if (loader?.loader === cssLoader) {
      loader.options.modules = {
        auto: true
      }
    }
  })
})
```

I will be happy to cook the PR, please confirm that it is within project scope.

**Comment by Judahmeek** [comment]
@skyksandr According to CSS-Loader documentation [modules: undefined (the default value, which we're currently using)](https://github.com/webpack-contrib/css-loader#modules) & [modules: {auto: true}](https://github.com/webpack-contrib/css-loader#auto) result in the same behavior: `enable CSS modules for all files matching /\.module\.\w+$/i.test(filename) and /\.icss\.\w+$/i.test(filename) regexp.`

This makes me suspect your actual problem is elsewhere in your code-base.

**Comment by skyksandr** [comment]
@Judahmeek you're right. I don't know why it did not work without it before and why it work without it now.
