### ISSUE TITLE
Readme: conflict in prerequisites?

### ISSUE THREAD

**Issue by tagliala** [shakacode/shakapacker#41]
Hi,

just noticed that as per [prerequisites](https://github.com/shakacode/shakapacker#prerequisites), shakapacker requires Rails 2.7+ and Ruby 5.2+, but Rails 5.2 does not officially support Ruby 2.7 rails/rails#38426

Should this be considered a conflict or an unsupported combination?

**Comment by tomdracz** [comment]
Good spot @tagliala  !


Looks like requirement of Ruby 2.7 was introduced in https://github.com/rails/webpacker/pull/3156 as it's the minimum that Rails 7 supports.

This indeed creates bit if discrepancy in the requirements. I think we've got 2 months left of Ruby 2.6 before EOL.

I'll open a PR, since we've pretty much dropped Rails 5.2 support with Ruby requirement change, we might as well update the docs and gemspec.

**Comment by tomdracz** [comment]
Looking at this though, TECHNICALLY, Rails 5.2 doesn't discard 2.7 in the gemspec https://github.com/rails/rails/blob/5-2-stable/rails.gemspec This is why our tests running Rails 5.2 against Ruby 2.7 pass (although with deprecation warnings for kwargs).

So looks like you can still run this combo but you're likely to hit some problems along the way. Considering the mismatch, Rails team position on this (officially unsupported) and EOL incoming, I think we should look at Rails 6 as minimum in one of the upcoming releases. Thoughts @justin808?

**Comment by justin808** [comment]
Since the surface area of webpacker is small, we should support 5.2.
